config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.order(id: :desc)
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todos_path, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_path, status: :see_other, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.expect(todo: [ :task, :done, :priority ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<h1>Welcome to the todo rails app</h1>
<p>Here you can create, edit and delete your todos</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
    <a href="/" class="navbar-brand">Home</a>

    <div class="navbar-menu">
        <a href="/todos" class="navbar-link">Todos</a>
        <a href="/todos/new" class="navbar-link">Add Todo</a>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.css" />
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="form-container">
  <%= form_with(model: todo) do |form| %>
    <% if todo.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

        <ul>
          <% todo.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.text_area :task, class: "todo-input" %>

    <div class="todo-form-bottom">
      <%= form.select :priority, options_for_select([['🔴', 'High'], ['🟠', 'Medium'], ['🟡', 'Low']], selected: todo.priority) %>

      <%= form.submit "Save", class: "todo-submit" %>
    </div>
  <% end %>
</div>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <div class="todo-card">
    <div class="todo-card-top">
      <p><%= todo.task %></p>

      <% if todo.done %>
        <%= button_to "✓", todo_path(todo), method: :patch, params: { todo: { done: false } }, class: "todo-card-button-done" %>
      <% else %>
        <%= button_to "✗", todo_path(todo), method: :patch, params: { todo: { done: true } }, class: "todo-card-button-undone" %>
      <% end %>
    </div>

    <div class="todo-card-footer">
      <p>
        <% if todo.priority == "High" %>
          🔴
        <% elsif todo.priority == "Medium" %>
          🟠
        <% else %>
          🟡
        <% end %>
      </p>

      <div>
        <%= button_to "📒", todo_path(todo), method: :get, class: "icon-button" %> 
        <%= button_to "🖊️", edit_todo_path(todo), method: :get, class: "icon-button" %>
        <%= button_to "🗑", todo_path(todo), method: :delete, class: "icon-button" %>
      </div>
    </div>
  </div>
</div>

app/views/todos/edit.html.erb
<% content_for :title, "Editing todo" %>

<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

app/views/todos/index.html.erb
<% content_for :title, "Todos" %>

<h1>Todos</h1>

<p style="color: green"><%= notice %></p>

<div id="todos" class="todos">
  <% @todos.each do |todo| %>
    <%= render todo %>
  <% end %>
</div>

<p>
  <%= link_to "Add todo +", new_todo_path %>
</p>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>

<h1>New todo</h1>

<%= render "form", todo: @todo %>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>